// Need install extension:  REST Client

@url_dev = http://localhost:2050/v1/api

# POST Signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: d290adb7ef30b5c7c666820ce1a9e284ebd8db848ca00a9f645c2e1474d9865e1b10ed20dd455cbd6ff72b118871c3bb88955eaef01ddccb89209b4358013ba6

{
  "email": "shop3@gmail.com",
  "password": "123456",
  "name": "Shop 3"
}

